import Head from "next/head";
import Title from "../components/Title";
import { Container } from "../styles/home";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title title="NextJS TypeScript Template" />
    </Container>
  );
}
